# Generated by Django 6.0.2 on 2026-07-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("github_core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="githubaccount",
            table="github_core__github_account",
        ),
        migrations.AlterModelTable(
            name="githubactionsjob",
            table="github_core__github_actions_job",
        ),
        migrations.AlterModelTable(
            name="githubactionsrun",
            table="github_core__github_actions_run",
        ),
        migrations.AlterModelTable(
            name="githubapp",
            table="github_core__github_app",
        ),
        migrations.AlterModelTable(
            name="githubplatform",
            table="github_core__github_platform",
        ),
        migrations.AlterModelTable(
            name="githubrepository",
            table="github_core__github_repository",
        ),
        migrations.AlterModelTable(
            name="githubrunner",
            table="github_core__github_runner",
        ),
        migrations.AlterModelTable(
            name="githubworkflow",
            table="github_core__github_workflow",
        ),
        migrations.AlterModelTable(
            name="oidcissuer",
            table="github_core__oidc_issuer",
        ),
    ]
