# Generated by Django 6.0.2 on 2026-07-08 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("github_core", "0003_alter_githubaccount_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oidcissuer",
            name="entity",
        ),
        migrations.DeleteModel(
            name="HistoricalOidcIssuer",
        ),
        migrations.DeleteModel(
            name="OidcIssuer",
        ),
    ]
