# Generated by Django 6.0.8 on 2026-09-02 21:00 (makemigrations --dry-run, then quoted per repo style).
#
# github-core#47: the run payload carries created_at, run_attempt, actor and triggering_actor and
# the job payload carries created_at; the collector dropped every one of them. Queue time
# (run_started_at - created_at, started_at - created_at per job) and re-run awareness need them
# as columns, not as raw_payload_keys evidence that they existed.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_core", "0004_historicalrulesuite_rulesuite"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubactionsjob",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="githubactionsrun",
            name="actor_login",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="githubactionsrun",
            name="created_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="githubactionsrun",
            name="run_attempt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="githubactionsrun",
            name="triggering_actor_login",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="historicalgithubactionsjob",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgithubactionsrun",
            name="actor_login",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="historicalgithubactionsrun",
            name="created_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgithubactionsrun",
            name="run_attempt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgithubactionsrun",
            name="triggering_actor_login",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
