# Generated by Django 6.0.8 on 2026-09-02 20:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_core", "0005_github_action"),
        ("tap_grid", "0002_entitytype_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionsArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "artifact_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                ("size_in_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "digest",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                ("expired", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "head_sha",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "head_branch",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "github_core__actions_artifact",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalActionsArtifact",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "artifact_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                ("size_in_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "digest",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                ("expired", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "head_sha",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "head_branch",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical actions artifact",
                "verbose_name_plural": "historical actions artifacts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
