# Generated by Django 6.0.8 on 2026-09-03 16:56 (makemigrations --merge).
#
# Two PRs each added a 0005 the same day: #59 (0005_run_provenance_fields, merged 16:42Z) and
# #51's chain (0005_github_action … 0008_status_check, merged 16:47–16:48Z). Neither saw the
# other, so main had two leaf nodes and a fresh boot failed at migrate ("Conflicting migrations
# detected"). This empty merge joins them; nothing is renamed, so a database that applied
# either leaf first stays consistent.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("github_core", "0005_run_provenance_fields"),
        ("github_core", "0008_status_check"),
    ]

    operations = []
