# Generated by Django 6.0.8 on 2026-09-03 19:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_core", "0009_merge_0005_run_provenance_fields_0008_status_check"),
        ("tap_grid", "0002_entitytype_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="githubrepository",
            name="outputs_observability",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicalgithubrepository",
            name="outputs_observability",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="GithubPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "package_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "owner_login",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "purl",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1024
                    ),
                ),
                ("visibility", models.CharField(blank=True, default="", max_length=32)),
                ("version_count", models.IntegerField(blank=True, null=True)),
                (
                    "repository_full_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("html_url", models.URLField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "github_core__github_package",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GithubPackageVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "version_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "owner_login",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "package_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "package_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "purl",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1024
                    ),
                ),
                ("container_tags", models.JSONField(blank=True, default=list)),
                ("html_url", models.URLField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "github_core__github_package_version",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GithubRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "release_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=512)),
                ("is_draft", models.BooleanField(blank=True, null=True)),
                ("is_prerelease", models.BooleanField(blank=True, null=True)),
                ("is_latest", models.BooleanField(blank=True, null=True)),
                (
                    "author_login",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("target_sha", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("html_url", models.URLField(blank=True, default="", max_length=512)),
                ("asset_count", models.IntegerField(blank=True, null=True)),
                ("assets", models.JSONField(blank=True, default=list)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "github_core__github_release",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalGithubPackage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "package_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "owner_login",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "purl",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1024
                    ),
                ),
                ("visibility", models.CharField(blank=True, default="", max_length=32)),
                ("version_count", models.IntegerField(blank=True, null=True)),
                (
                    "repository_full_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("html_url", models.URLField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical github package",
                "verbose_name_plural": "historical github packages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGithubPackageVersion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "version_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "owner_login",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "package_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "package_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "purl",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1024
                    ),
                ),
                ("container_tags", models.JSONField(blank=True, default=list)),
                ("html_url", models.URLField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical github package version",
                "verbose_name_plural": "historical github package versions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGithubRelease",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "release_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=512)),
                ("is_draft", models.BooleanField(blank=True, null=True)),
                ("is_prerelease", models.BooleanField(blank=True, null=True)),
                ("is_latest", models.BooleanField(blank=True, null=True)),
                (
                    "author_login",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("target_sha", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("html_url", models.URLField(blank=True, default="", max_length=512)),
                ("asset_count", models.IntegerField(blank=True, null=True)),
                ("assets", models.JSONField(blank=True, default=list)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical github release",
                "verbose_name_plural": "historical github releases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
