# Generated by Django 6.0.8 on 2026-09-08 22:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_core', '0011_retire_git_ref_and_git_commit_rows'),
        ('tap_grid', '0002_entitytype_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitref',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='historicalgitcommit',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='historicalgitcommit',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalgitref',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='historicalgitref',
            name='history_user',
        ),
        migrations.CreateModel(
            name='CommitObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, db_index=True, default='', help_text='UUIDv7 of the batch this change was included in.', max_length=36)),
                ('flip_map', models.JSONField(blank=True, default=dict, help_text='FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.')),
                ('full_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('repository_github_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('hash_algorithm', models.CharField(blank=True, default='sha1', max_length=16)),
                ('sha', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('author_login', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('committer_login', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('signature_kind', models.CharField(blank=True, default='', max_length=16)),
                ('signature_state', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('signature_valid', models.BooleanField(blank=True, null=True)),
                ('signer_login', models.CharField(blank=True, default='', max_length=255)),
                ('signed_by_github', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tap_grid.entity')),
            ],
            options={
                'db_table': 'github_core_commit_observation',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCommitObservation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, db_index=True, default='', help_text='UUIDv7 of the batch this change was included in.', max_length=36)),
                ('flip_map', models.JSONField(blank=True, default=dict, help_text='FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.')),
                ('full_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('repository_github_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('hash_algorithm', models.CharField(blank=True, default='sha1', max_length=16)),
                ('sha', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('author_login', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('committer_login', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('signature_kind', models.CharField(blank=True, default='', max_length=16)),
                ('signature_state', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('signature_valid', models.BooleanField(blank=True, null=True)),
                ('signer_login', models.CharField(blank=True, default='', max_length=255)),
                ('signed_by_github', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tap_grid.entity')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical commit observation',
                'verbose_name_plural': 'historical commit observations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='GitCommit',
        ),
        migrations.DeleteModel(
            name='GitRef',
        ),
        migrations.DeleteModel(
            name='HistoricalGitCommit',
        ),
        migrations.DeleteModel(
            name='HistoricalGitRef',
        ),
    ]
