# Generated by Django 6.0.8 on 2026-09-08 23:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_core", "0014_github_custom_property"),
        ("tap_grid", "0002_entitytype_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="githubrepository",
            name="pull_requests_observability",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="githubrepository",
            name="pull_requests_total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalgithubrepository",
            name="pull_requests_observability",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="historicalgithubrepository",
            name="pull_requests_total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HistoricalPullRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("number", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "github_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=16
                    ),
                ),
                ("is_draft", models.BooleanField(default=False)),
                (
                    "author_login",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "author_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "author_association",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("head_ref", models.CharField(blank=True, default="", max_length=255)),
                (
                    "head_sha",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "head_repository",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("base_ref", models.CharField(blank=True, default="", max_length=255)),
                ("base_sha", models.CharField(blank=True, default="", max_length=64)),
                (
                    "review_decision",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("mergeable", models.CharField(blank=True, default="", max_length=16)),
                (
                    "merge_commit_sha",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("commit_count", models.IntegerField(blank=True, null=True)),
                ("additions", models.IntegerField(blank=True, null=True)),
                ("deletions", models.IntegerField(blank=True, null=True)),
                ("changed_files", models.IntegerField(blank=True, null=True)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("review_requests", models.JSONField(blank=True, default=list)),
                ("latest_reviews", models.JSONField(blank=True, default=list)),
                (
                    "checks_rollup_state",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=16
                    ),
                ),
                ("checks", models.JSONField(blank=True, default=list)),
                (
                    "checks_observability",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("html_url", models.URLField(blank=True, default="", max_length=512)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pull request",
                "verbose_name_plural": "historical pull requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("number", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "github_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=16
                    ),
                ),
                ("is_draft", models.BooleanField(default=False)),
                (
                    "author_login",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "author_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "author_association",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("head_ref", models.CharField(blank=True, default="", max_length=255)),
                (
                    "head_sha",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "head_repository",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("base_ref", models.CharField(blank=True, default="", max_length=255)),
                ("base_sha", models.CharField(blank=True, default="", max_length=64)),
                (
                    "review_decision",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("mergeable", models.CharField(blank=True, default="", max_length=16)),
                (
                    "merge_commit_sha",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("commit_count", models.IntegerField(blank=True, null=True)),
                ("additions", models.IntegerField(blank=True, null=True)),
                ("deletions", models.IntegerField(blank=True, null=True)),
                ("changed_files", models.IntegerField(blank=True, null=True)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("review_requests", models.JSONField(blank=True, default=list)),
                ("latest_reviews", models.JSONField(blank=True, default=list)),
                (
                    "checks_rollup_state",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=16
                    ),
                ),
                ("checks", models.JSONField(blank=True, default=list)),
                (
                    "checks_observability",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("html_url", models.URLField(blank=True, default="", max_length=512)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "github_core__pull_request",
                "abstract": False,
            },
        ),
    ]
