# Generated by Django 6.0.8 on 2026-09-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_core", "0018_collection_scope"),
        ("tap_grid", "0005_entity_natural_key_clear"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="actionsartifact",
            index=models.Index(
                fields=["full_name", "artifact_id"],
                name="nk_github_core__action_5b40a61",
            ),
        ),
        migrations.AddIndex(
            model_name="actionscache",
            index=models.Index(
                fields=["full_name", "cache_id"], name="nk_github_core__actions_cache"
            ),
        ),
        migrations.AddIndex(
            model_name="actionssecret",
            index=models.Index(
                fields=[
                    "scope",
                    "owner_login",
                    "full_name",
                    "environment_name",
                    "name",
                ],
                name="nk_github_core__actions_secret",
            ),
        ),
        migrations.AddIndex(
            model_name="codescanningalert",
            index=models.Index(
                fields=["full_name", "number"], name="nk_github_core__code_s_89a1145"
            ),
        ),
        migrations.AddIndex(
            model_name="codescanninganalysis",
            index=models.Index(
                fields=["full_name", "analysis_id"],
                name="nk_github_core__code_s_53b7ade",
            ),
        ),
        migrations.AddIndex(
            model_name="commitobservation",
            index=models.Index(
                fields=["repository_github_id", "hash_algorithm", "sha"],
                name="nk_github_core_commit__1524d3a",
            ),
        ),
        migrations.AddIndex(
            model_name="githubactionsjob",
            index=models.Index(
                fields=["full_name", "job_id"], name="nk_github_core__github_2bd97dd"
            ),
        ),
        migrations.AddIndex(
            model_name="githubactionsrun",
            index=models.Index(
                fields=["full_name", "run_id"], name="nk_github_core__github_9d89857"
            ),
        ),
        migrations.AddIndex(
            model_name="githubcustomproperty",
            index=models.Index(
                fields=["owner_login", "property_name"],
                name="nk_github_core__github_d259e31",
            ),
        ),
        migrations.AddIndex(
            model_name="githubenvironment",
            index=models.Index(
                fields=["full_name", "name"], name="nk_github_core__github_dc971f3"
            ),
        ),
        migrations.AddIndex(
            model_name="githubpackage",
            index=models.Index(
                fields=["owner_login", "package_type", "name"],
                name="nk_github_core__github_package",
            ),
        ),
        migrations.AddIndex(
            model_name="githubpackageversion",
            index=models.Index(
                fields=["owner_login", "package_type", "package_name", "version_id"],
                name="nk_github_core__github_6887da3",
            ),
        ),
        migrations.AddIndex(
            model_name="githubrelease",
            index=models.Index(
                fields=["full_name", "release_id"],
                name="nk_github_core__github_release",
            ),
        ),
        migrations.AddIndex(
            model_name="githubruleset",
            index=models.Index(
                fields=["owner_login", "ruleset_id"],
                name="nk_github_core__github_ruleset",
            ),
        ),
        migrations.AddIndex(
            model_name="githubrunner",
            index=models.Index(
                fields=["full_name", "runner_id"], name="nk_github_core__github_runner"
            ),
        ),
        migrations.AddIndex(
            model_name="githubworkflow",
            index=models.Index(
                fields=["full_name", "workflow_id"],
                name="nk_github_core__github_79c2bbc",
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(
                fields=["full_name", "number"], name="nk_github_core__pull_request"
            ),
        ),
        migrations.AddIndex(
            model_name="statuscheck",
            index=models.Index(
                fields=["owner_login", "context"], name="nk_github_core__status_check"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowjob",
            index=models.Index(
                fields=["full_name", "workflow_id", "job_key"],
                name="nk_github_core__workflow_job",
            ),
        ),
    ]
