# Generated by Django 6.0.8 on 2026-09-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_core", "0019_natural_key_indexes"),
        ("tap_grid", "0005_entity_natural_key_clear"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="commitobservation",
            name="nk_github_core_commit__1524d3a",
        ),
        migrations.AddField(
            model_name="commitobservation",
            name="host",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="historicalcommitobservation",
            name="host",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddIndex(
            model_name="commitobservation",
            index=models.Index(
                fields=["host", "repository_github_id", "hash_algorithm", "sha"],
                name="nk_github_core_commit__1524d3a",
            ),
        ),
    ]
