# Generated by Django 6.0.8 on 2026-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_core", "0020_commit_observation_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionssecret",
            name="name_reported",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="historicalactionssecret",
            name="name_reported",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
